### ISSUE TITLE
Clean prefixes

### ISSUE THREAD

**Issue by adityamj** [sphinx-contrib/confluencebuilder#316] opened 2020-04-17 16:24 UTC
Hi,

I am trying to have clean prefixes as demonstrated at https://jdknight.atlassian.net/wiki/spaces/confluencebuilder/overview

The demonstration has clean top level prefix like 1.2v and other pages have 1.2v-

I am unable to remove the hyphen from the top level index page. My top level page looks like "1.1v-"

Is there a way to have clean prefixes like you have shown in the demonstration?

Thanks,
Aditya

**Comment by jdknight** [comment] 2020-04-29 04:36
@adityamj, the [`confluence_publish_prefix`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-publish-prefix) option should be just a direct prefix on document title values, so a configuration such as:

```
confluence_publish_prefix = '1.2v-'
```

Should be a translated to `1.2v-<generated-title-value>`. Based on your comments, I would suspect that either the following is happening:

1. You may have [`confluence_add_secnumbers`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-add-secnumbers) enabled (by default) and which may not actually be a desired feature for your use case.
2. You may have invoked a publish attempt multiple times with various `confluence_publish_prefix` values; however, this will not remove older published documents by default (see also [`confluence_purge`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-purge)).

If neither is what you are experiencing, could you then provide more information? Hopefully we can sort out the root cause here (ambiguous configuration/documentation or an actual bug in the extension).

**Comment by adityamj** [comment] 2020-04-29 08:02
Hi, thanks for taking the time to go through this issue! 

So here is my setup: 

1. Each tag/branch gets its own prefix. For example master branch has
the prefix 'master-', v3.1 has prefix 'v3.1-' and so on.
2. All these versions are uploaded under a page in confluence. 

Here is how the menu structure looks: 

* Top level page
   * master-
      *master-introduction
      *master-some other page etc
   * v3.1-
      *v-3.1-introduction 

and so on. 

Secnumbers are disabled in my toctree so that is not the issue. 

What I would like is for the menu to look like: 

* Top level page
   * master
      *master-introduction
      *master-some other page etc
   * v3.1
      *v-3.1-introduction 

Here, the "-" from prefix is not there in branches' top level page
however it is still there in pages lower in the tree. 

This is just an aesthetic issue so that top level pages don't have a
dangling "-". 

I see this being done on
https://jdknight.atlassian.net/wiki/spaces/confluencebuilder/overview
where there is no suffix "-" on top level page but it is there in pages
under the top level page. 

* v1.2
  * v1.2-auto-extensions 

One way is to manually remove the suffix "-" after the upload so that
"master-"  becomes "master". Since this doc is prepared from
confluencebuilder itself, I was wondering if I am missing a config
parameter that could enable such a behavior for my confluence uploads.

**Comment by jdknight** [comment] 2020-05-22 03:46
@adityamj, I assume the difference between the published validation set versus your setup is that the "root" pages in the validation set are actually manually created pages. These manually created pages serve as the containers ([`confluence_parent_page`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-parent-page)) where the Sphinx-generated content is stored in -- hence why there is no prefix appended to those pages.

At this time, there is not an immediate solution for you other than manually creating the parent pages yourself or (as you have suggested) manually tweaking the root page's title after publication. This extension could introduce an option such as `confluence_ignore_titlefix_on_master` to help deal with this scenario. Curious though, if this documentation set is producing a a root title page `master-` and is configured with a prefix `master-`, is this example set not defining a default title inside the `master_doc`?

**Comment by adityamj** [comment] 2020-05-22 04:18
Thanks! That makes sense now. 
Titles are working fine at the master level.
 I would be happy to contribute the flag :)

**Comment by jdknight** [comment] 2020-11-26 23:05
With the changes introduced in #349, the configuration option `confluence_ignore_titlefix_on_index` should prevent this issued use case from occurring now. This option is available on the development branch and will be available in v1.3+ release.

If it is determined that this option does not completely address the concerns mentioned here, please feel free to mention it. Otherwise this issue will be closed upon the release of v1.3.

**Comment by adityamj** [comment] 2020-11-27 13:39
Thank you, the flag addresses my use case.

**Comment by jdknight** [comment] 2021-01-01 01:14
v1.3 is now available on PyPI -- marking as closed.

**Closed by jdknight** 2021-01-01 01:14 UTC
