### ISSUE TITLE
any support for the new confluence editor

### ISSUE THREAD

**Issue by ghost** [sphinx-contrib/confluencebuilder#312] opened 2020-03-19 13:04 UTC
Hi,

We are using the builder to create documents in confluence and it is working fine until the confluence changed to the new editor.

Here is the error we are getting in our builds.

sphinxcontrib.confluencebuilder error:
---
An unsupported Confluence API call has been made.
REQ: PUT
RSP: 400
URL: https://myrepo.atlassian.net/wiki/rest/api
API: content
DATA: {
  "statusCode": 400,
  "data": {
    "authorized": false,
    "valid": true,
    "errors": [],
    "successful": false
  },
  "message": "com.atlassian.confluence.api.service.exceptions.BadRequestException: Content body cannot be converted to new editor format"
}

Is there anyone getting the same problem or anyone working on it to get it fixes?

Thanks in advance.

**Comment by mischkew** [comment] 2020-03-24 16:30
We do encounter the same error. I'll gladly provide debug output, what would you need in order to reproduce this on your side? I can try to create a minimal example?

**Comment by jdknight** [comment] 2020-03-24 23:02
@mapperkids, @mischkew and anyone else following this issue,

Based off the comments provided, it looks like Atlassian now attempts for force-convert storage format content into the newer Atlassian document format. It was partially looked at in issue #229; however, it was assumed there would be more time to support both the document format types. Clearly, that is no longer the case. At this time, it appears that publishing will no longer work on Confluence Cloud and possibly Confluence Server editions v7.3+ until a future release.

Unfortunately, this is a non-trivial fix. This extension will need to introduce a new translator support to handle the new document format. And existing users may also need to be aware that there will be many Sphinx/reStructutedText capabilities that can no longer be supported with Atlassian's new document structure (e.g. complex paragraph indentations, nested tables, etc.; that is unless Atlassian has re-introduced capabilities to style content again).

There is a plan to introduce support for the new document format type. The unfortunate news is that there may not be a v1.3 release until end of April. This is primarily due to recent events that most (if not all of us) are experiencing.

**Comment by mapperkids** [comment] 2020-03-25 00:53
> @mapperkids, @mischkew and anyone else following this issue,
> 
> Based off the comments provided, it looks like Atlassian now attempts for force-convert storage format content into the newer Atlassian document format. It was partially looked at in issue #229; however, it was assumed there would be more time to support both the document format types. Clearly, that is no longer the case. At this time, it appears that publishing will no longer work on Confluence Cloud and possibly Confluence Server editions v7.3+ until a future release.
> 
> Unfortunately, this is a non-trivial fix. This extension will need to introduce a new translator support to handle the new document format. And existing users may also need to be aware that there will be many Sphinx/reStructutedText capabilities that can no longer be supported with Atlassian's new document structure (e.g. complex paragraph indentations, nested tables, etc.; that is unless Atlassian has re-introduced capabilities to style content again).
> 
> There is a plan to introduce support for the new document format type. The unfortunate news is that there may not be a v1.3 release until end of April. This is primarily due to recent events that most (if not all of us) are experiencing.

@jdknight thanks for the reply and totally understood, we shall wait for the new release then. Thanks again!

**Comment by jdknight** [comment] 2020-06-11 03:20
@mapperkids, out of curiosity, do you still see this issue?

Was beginning to look at supporting a new translator when it was observed that the validation set could still be published to Confluence Cloud. This makes me assume the Atlassian still supports the storage format for new documents.

Some additional searching led me to the following issue:

> [CONFCLOUD-69720](https://jira.atlassian.com/browse/CONFCLOUD-69720)
> Using REST API to update a page fails with a misleading error message if no user-agent is provided

This issue (along with other Q&A pages) shows that users are experiencing the "Content body cannot be converted to new editor format" error (mentioning in this initial issue comment) is an indication of Confluence not handling a request without a user agent. It looks to be fixed, hence the inquiry to see if this issue can still be experienced. I do have a pending change which will include a user agent value (just in case a specific Confluence version make still have this issue).

**Comment by jdknight** [comment] 2020-06-11 06:09
(see also #325)

**Comment by zed-eiq** [comment] 2020-06-22 20:02
i am interested and can try to replicate this on a more recent confluence server version. my team is planning an upgrade and i'll be doing my own tests -- will share my results if helpful!

btw, thanks for your work on this. it's been a lifesaver 🎉

**Comment by zed-eiq** [comment] 2020-06-24 11:56
works for me, publishing from a sphinx private repo to confluence server 7.4.0

**Comment by JavierLopezT** [comment] 2020-09-15 08:26
I am currently getting this error with Confluence Cloud. My version of confluencebuilder is the last one (1.2.0), so I guess the patch #325 you made @jdknight should work but it doesn't. How could I try to debug this? Thank you very much in advance

**Comment by jdknight** [comment] 2020-10-26 01:08
Note that the error associated with this issues initial message is associated with [CONFCLOUD-69720](https://jira.atlassian.com/browse/CONFCLOUD-69720) (see the [above comment](https://github.com/sphinx-contrib/confluencebuilder/issues/312#issuecomment-642381715)). Since this issue was fixed on Confluence Cloud with the additional changes made with #325, it is assumed the issue has been resolved. Users on Confluence Cloud should be good to go. If a user is experiencing issues with a Confluence Server revision which is affected with this bug, they can either use the bleeding-edge sources, or can wait for a v1.3 release planned before the end-of-year. Thanks for the report.

Note that the unsupported Confluence API (500) error also discussed in this thread is unrelated and can be tracked on #348 instead. Further comments can be added to #348 and this issue will be closed.

**Closed by jdknight** 2020-10-26 01:08 UTC
