### ISSUE TITLE
Wrong type in error logging

### ISSUE THREAD

**Issue by konradbender** [sphinx-contrib/confluencebuilder#632] opened 2022-03-07 15:21 UTC
Hi there,

I am using the rate limiting feature introduced in #625. I believe that a recent PR might have broken that feature, because I am getting the error below:

``` cat sphinx-err-3hfrwz6_.log 
# Sphinx version: 4.4.0
# Python version: 3.8.10 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.3
# Last messages:
#   writing output... [ 52%] autoapi/<module_name>
#   writing output... [ 58%] autoapi/<module_name>
#   writing output... [ 64%] autoapi/<module_name>
#   writing output... [ 70%] autoapi/<module_name>
#   writing output... [ 76%] autoapi/<module_name>
#   writing output... [ 82%] contribute
#   writing output... [ 88%] index
#   writing output... [ 94%] usage
#   writing output... [100%] write_docu
#   
# Loaded extensions:
#   sphinx.ext.mathjax (4.4.0) from /home/ubuntu/.local/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/ubuntu/.local/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/ubuntu/.local/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /home/ubuntu/.local/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /home/ubuntu/.local/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/ubuntu/.local/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/ubuntu/.local/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /home/ubuntu/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.4.0) from /home/ubuntu/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.4.0) from /home/ubuntu/.local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (4.4.0) from /home/ubuntu/.local/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinxcontrib.confluencebuilder (1.8.0.dev0) from /home/ubuntu/.local/lib/python3.8/site-packages/sphinxcontrib/confluencebuilder/__init__.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_all()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 258, in build_all
    self.build(None, summary=__('all source files'), method='all')
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.finish()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sphinxcontrib/confluencebuilder/builder.py", line 690, in finish
    self.parent_id = self.publisher.get_base_page_id()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sphinxcontrib/confluencebuilder/publisher.py", line 171, in get_base_page_id
    rsp = self.rest_client.get('content', {
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sphinxcontrib/confluencebuilder/rest.py", line 84, in _wrapper
    'waiting {} seconds...'.format(math.ceil(delay)))
TypeError: must be real number, not str
```

Let me know if you need any more information!

**Comment by jdknight** [comment] 2022-03-09 06:19
The issue is specific to the line where [`next_delay` is set from the header value](https://github.com/sphinx-contrib/confluencebuilder/blob/fa248d3b33a8940af369289e8c512370c7c67ba6/sphinxcontrib/confluencebuilder/rest.py#L334).

This line needs to be improved to properly parse the [`Retry-After`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) header -- not only trying to parse an integer-string value to an integer; but also handling the case where a proxy may opt to specifying a [`Date`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date) value.

A quick-hack (if needed) would be to comment/remove that line, where this extension will fallback to the automatic rate limiting managed in the extension.

**Comment by jdknight** [comment] 2022-03-16 04:09
There should be a fix for the rate-delay feature in #634. If you're interested to try it, the following command would install the development change:

```
pip install git+https://github.com/sphinx-contrib/confluencebuilder.git@accept-expected-rate-limiting-retry-after-values
```

The plan is to merge this in, but if you observe any issues with this, please let me know.

**Comment by konradbender** [comment] 2022-03-16 11:21
Very cool, thank you!

I ran it in verbose mode with the following settings in `conf.py` 
```
confluence_publish_delay = 0.5

confluence_publish_headers = {
    'Connection': 'close',
}
```

and this is the pattern I am gett what I am getting in the output:

```
publishing documents... [ 30%] <page_1_name>
[confluence] user-set api delay set; waiting 1 seconds...
[confluence] rate-limit header detected; waiting 29 seconds...
[confluence] user-set api delay set; waiting 1 seconds...
[confluence] user-set api delay set; waiting 1 seconds...
[confluence] rate-limit header detected; waiting 29 seconds...
[confluence] tracking docname <page_1_name> upload id: 2087409277
publishing documents... [ 33%] <page_2_name>
[confluence] user-set api delay set; waiting 1 seconds...
[confluence] rate-limit header detected; waiting 29 seconds...
[confluence] user-set api delay set; waiting 1 seconds...
[confluence] user-set api delay set; waiting 1 seconds...
[confluence] rate-limit header detected; waiting 29 seconds...
[confluence] tracking docname <page_2_name> upload id: 2087409292
publishing documents... [ 36%] <page_3_name>
```
This then repeats for every page that is published.

**Comment by jdknight** [comment] 2022-03-16 14:25
Thanks for trying it out, and sharing the results.

Yeah, looks like the proxy is forcing retries to every 30 seconds. 😬

In theory, you should no longer have to set `confluence_publish_delay` any more, which should reduce some time in a publishing event (the delay stuff should be handling the proper count; and an internal jitter logic should help with any additional offset/timing stuff).

You could also probably drop the `Connection` option inside `confluence_publish_headers` as well. I would imagine your interaction would be the same for now (although, debug logging may show more information). But in time, if the proxy you work with permits a keep-alive connection, your configuration would be already ready to utilize it.

**Comment by jdknight** [comment] 2022-03-27 18:00
v1.8 is now available on PyPI -- marking as closed.

**Closed by jdknight** 2022-03-27 18:00 UTC
Labels: bug, pending next release
