### ISSUE TITLE
Publish to parent page that is not root

### ISSUE THREAD

**Issue by g-simmons** [sphinx-contrib/confluencebuilder#444] opened 2021-02-28 22:46 UTC
Hi, is it possible through some config settings to publish to a parent page that is not in the root of the target space? For example if I have a confluence hierarchy where A is the root, and I have B, C, and B1 as existing pages, can I publish my sphinx docs as B1.1, B1.2?

```
A
├── B
│   └── B1
│       ├── B1.1
│       └── B1.2
└── C
```

**Comment by g-simmons** [comment] 2021-02-28 23:06
Works with the following edit to [publisher.py](https://github.com/sphinx-contrib/confluencebuilder/blob/66d45959c8e6e7e3761d95bc8a64d45cd89cad75/sphinxcontrib/confluencebuilder/publisher.py#L58):

I'd be happy to work on a PR with some guidance. Maybe add an additional parameter like `force_parent_in_root` to determine whether to search all descendants or just direct descendants?

```
    def getBasePageId(self):
        base_page_id = None

        descendants = self.getDescendants(None)

        for descendant in descendants:
            if self._name_cache[descendant] == self.parent_name:
                if self.parent_id is not None:
                    if descendant == self.parent_id:
                        base_page_id = descendant
                else:
                    base_page_id = descendant

        # if not self.parent_name:
        #     return base_page_id

        # rsp = self.rest_client.get('content', {
        #     'type': 'page',
        #     'spaceKey': self.space_name,
        #     'title': self.parent_name,
        #     'status': 'current'
        # })
        # if rsp['size'] == 0:
        #     raise ConfluenceConfigurationError("""Configured parent """
        #         """page name do not exist.""")
        # page = rsp['results'][0]
        # if self.parent_id and page['id'] != str(self.parent_id):
        #     raise ConfluenceConfigurationError("""Configured parent """
        #         """page ID and name do not match.""")
        # base_page_id = page['id']
        # self._name_cache[base_page_id] = self.parent_name

        if not base_page_id:
            raise ConfluenceConfigurationError("""Unable to find the """
                """parent page matching the ID or name provided.""")

        return base_page_id
```

**Comment by jdknight** [comment] 2021-03-20 17:39
I may not be understanding this request exactly, but my first impression is that this is achieved using the [`confluence_parent_page`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration.html#confval-confluence_parent_page) configuration. For example, with you existing page setup (mentioned above):

```
A
├── B
│   └── B1
└── C
```

And using a configuration such as the following:

```
confluence_parent_page = 'B1'
```

Any new documents will be published under the `B1` "container":


```
│   └── B1 (container)
│       ├── B1.1 (newly published/updated)
│       └── B1.2 (newly published/updated)
```

Although, if you are looking to replace the content of `B1` as the main document of your documentation set, we can consider this a duplicate of #439. If I have misunderstood this request, please feel free to correct me.

**Comment by jdknight** [comment] 2021-05-30 06:06
It is assumed with either use of the [`confluence_parent_page`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration.html#confval-confluence_parent_page) configuration (with a possible [`confluence_publish_prefix`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration.html#confval-confluence_publish_prefix) usage) or using the recently added (v1.5) [`confluence_publish_root`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration.html#confluence-publish-root) configuration, the inquiry mentioned in this issue can be achieved. Therefore, will go ahead and close this issue.

If this is not the case, please feel free to comment.

**Closed by jdknight** 2021-05-30 06:06 UTC
