### ISSUE TITLE
Unsupported Confluence API call

### ISSUE THREAD

**Issue by svantis** [sphinx-contrib/confluencebuilder#330] opened 2020-06-12 14:25 UTC
When confluence_parent_page = 'parent' is set in my conf.py file and I 'make confluence' I get the following error message:

phinxcontrib.confluencebuilder error:
---
An unsupported Confluence API call has been made.

REQ: PUT
RSP: 500
URL: http://localhost:8090/rest/api
API: content
DATA: {
  "statusCode": 500,
  "message": "",
  "reason": "Internal Server Error"
}
---

make: *** [Makefile:20: confluence] Error 2

I have a page called 'parent' in my space

When confluence_publish_prefix is set, the issue seems to disappear

**Comment by jdknight** [comment] 2020-07-26 04:59
@svantis, a 500 series error from a Confluence instance can mean multiple things. Unfortunately, to get the explicit error (if any), would be to consult the logs on the instance itself (which may not always be available for most users).

Typically though, the primary reason why a 500 error has been observed in the past is when there is an attempt to make a parent page a child of child page. For example, if you had a container page on a space called `parent` and also have a page in your documentation set called `parent`, this could put you in a situation where this extension will attempt to move a page into an invalid state. This may be the case since you have been able to publish while setting a prefix value.

Other than that, I do not see much else that could provide a hint at what the issue is. You could attempt to invoke the build request with more verbose messages (appending `-vvv` on the command line) and seeing if it reveals anything helpful.

**Comment by jdknight** [comment] 2020-10-26 01:12
These undefined publish states have been reported by multiple users and improves to this extension should be made to improve the user experience. To cover the feature change to do this, a new issue (#348) has been made with a more explicit goal. Thanks for reporting this and hopefully an update can be made to prevent this ambiguous error in the future. Any further comments on this issue should be discussed in #348; marking as closed.

**Closed by jdknight** 2020-10-26 01:12 UTC
