### ISSUE TITLE
Force generation of TOC in singleconfluence

### ISSUE THREAD

**Issue by tsvi** [sphinx-contrib/confluencebuilder#447] opened 2021-03-08 15:11 UTC
Is it possible to force the generation of a TOC when using the `singleconfluence` builder?

**Comment by jdknight** [comment] 2021-03-20 18:59
Unfortunately, it does not look like it is possible at this time. This extension uses Sphinx's `inline_all_toctrees` utility call (in the same manner as the `singlehtml` builder uses) which will just [replace the toctree node](https://github.com/sphinx-doc/sphinx/blob/5e8f814e81ef11da9efc48f4efd6647c5bfa4596/sphinx/util/nodes.py#L431) with the content of the documents tied to that tree. This may relate to sphinx-doc/sphinx#1863.

It may be possible to mimic that call and attempt to keep the original table/references being replaced, but it is known off hand if it is a trivial or something complex to manage.

**Comment by tsvi** [comment] 2021-04-11 08:09
I was wondering maybe we could leverage [the `process_tree_structure` code from the regular builder](https://github.com/sphinx-contrib/confluencebuilder/blob/ea750e2b8edca7bb176c468807c41526b11a9d8d/sphinxcontrib/confluencebuilder/builder.py#L317).
We could insert a call to it [right before the call to `inline_all_toctrees`](https://github.com/sphinx-contrib/confluencebuilder/blob/ea750e2b8edca7bb176c468807c41526b11a9d8d/sphinxcontrib/confluencebuilder/singlebuilder.py#L28) and insert the generated TOC as a new node in the doc.

I was thinking of implementing it myself, but I'm not really sure how to set up a dev environment for Sphinx in general/confluencebuilder specific.

Any thoughts?

**Comment by jdknight** [comment] 2021-04-11 16:36
A recommendation, if there is an interest to look at the betterment of not only this extension but also Sphinx (and its builders/extensions), is that a good goal would actually be trying to resolve sphinx-doc/sphinx#1863; or at least, providing utility call changes in Sphinx the ability for any builder to support the ability to inline toctree's while maintaining the original toctree information. This assumes that the Sphinx team would accept/desire such a feature, which may be likely since the issue is currently tracked as a proposal.

That all being said, this may be out of your own desired scope -- if you want to focus solely on the extension, it is fine by me. Answers to the questions mentioned above will follow in the tail part of this response.

---

**_(NOTE: the following will only work with a fixed mentioned in #457)_**

Took some time the other day to look at this request, and there was some _partial_ success at attempting to manipulate Sphinx's [`inline_all_toctrees`](https://github.com/sphinx-doc/sphinx/blob/5e8f814e81ef11da9efc48f4efd6647c5bfa4596/sphinx/util/nodes.py#L401) call. Replacing the line:

```
toctreenode.parent.replace(toctreenode, newnodes)
```

With something like the following:

```
resolved_tree = builder.env.get_and_resolve_doctree(docname, builder,
    prune_toctrees=True, includehidden=False)
toctreenode.replace_self(resolved_tree)

for node in newnodes:
    toctreenode.parent.append(node)
```

The result will be doctree which includes both the resolved toctree nodes and the inlined content for each document. However, this change is not complete -- quick checks when inspecting a `singlehtml` builder shows that the toctree contents may be rendered twice (although, not observed in the `singleconfluence` builder).

Assuming this approach is desired and the `inline_all_toctrees` call can be adjusted in a way to support keeping TOC data without breaking existing builders, the call can then be adjusted to accept a new argument which can flag whether or not a builder wants to maintain or remove TOC data from any inlined doctree. In turn, this and other extension could use an official way to deal with this feature (this extension could later introduce a compatibility change to help support older Sphinx engines which do not have this feature).

---

> maybe we could leverage [the `process_tree_structure` code from the regular builder

It may be best to avoid using the `process_tree_structure` call. Its goals are to just determine publishing order and dealing with content squashing (a feature which may go away in the future due to the maintenance involved in manipulating the environment's `get_doctree` call and related).

If the goal is just to manipulate the generated doctree, the best location would be to focus on these lines in the `SingleConfluenceBuilder` implementation:

```
tree = self.env.get_doctree(master)
tree = inline_all_toctrees(self, set(), master, tree, darkgreen, [master])
```

The first call gets the doctree from the project's main document and the second call provides a new processed doctree for the final content. Adjusting/replacing the second call would be the right place to try to do any manipulation for the end goal here.

> I was thinking of implementing it myself, but I'm not really sure how to set up a dev environment for Sphinx in general/confluencebuilder specific.

Help towards this extension or to Sphinx is always welcome. Feel free to ask questions here (for this extension) and the Sphinx project has a mailing list/IRC channel as well. If you are planning to contribute to this extension, it is recommended to read the [CONTRIBUTING](https://github.com/sphinx-contrib/confluencebuilder/blob/master/CONTRIBUTING.rst) document at some point.

If you are looking for a quick/crude way to get an environment setup for working with this extension, the following hints may help:

1. Install [Python](https://www.python.org/) in your development environment.
2. Install [tox](https://tox.readthedocs.io/) for your Python interpreter.
3. Clone this project's repository (either directly or from a fork).
4. Drop the example documentation you want to work with into the `sandbox` folder.
5. Invoke `tox -e sandbox -- --builder singlehtml` to invoke a `singlehtml` build of the content. You can inspect the results under the local `output/` folder.
6. Finally, invoke `tox -e sandbox -- --builder singleconfluence` to invoke the `singleconfluence` builder.

I hope this help.

**Comment by jdknight** [comment] 2021-11-11 23:03
Support for leaving resolved TOC tree entries when using the `singleconfluence` builder has been added in #547; currently on the development branch and should be available next release (v1.7+). Please feel free to try it out by using the bleeding edge sources (if desired) and report any issues you may experience.

**Comment by tsvi** [comment] 2021-11-14 13:52
Hey, @jdknight that's wonderful news. I'll definitely check it out once you get 1.7 released.
I'd like to send you a tip for fixing this. How can I do so?

**Comment by jdknight** [comment] 2021-11-15 01:30
@tsvi, appreciated, but not needed. Testing and reporting issues/limitations to help the community is good enough for me.

**Comment by jdknight** [comment] 2021-11-21 20:39
v1.7 is now available on PyPI -- marking as closed.

**Closed by jdknight** 2021-11-21 20:39 UTC
Labels: enhancement, pending next release

**Comment by tsvi** [comment] 2021-11-22 10:57
Just tested it. Solved our case. Thanks again.
