### ISSUE TITLE
sphinxcontrib-confluencebuilder is not compatible with Sphinx-diagrams

### ISSUE THREAD

**Issue by AndreasLuckert** [sphinx-contrib/confluencebuilder#594] opened 2021-12-01 16:09 UTC
### Describe the bug

I ran this command in bash to build the sphinx docs and push them to confluence:
`sphinx-build -E -a docs/source docs/build/confluence -b confluence`

The error-logfile has the following output:

```
# Sphinx version: 4.2.0
# Python version: 3.9.4 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.3
# Last messages:
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  6%] apidoc/ics
#   writing output... [ 12%] apidoc/ics.plugins
#   writing output... [ 18%] apidoc/modules
#   writing output... [ 25%] architecture
# Loaded extensions:
#   sphinx.ext.mathjax (4.2.0) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.2) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.3) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from c:\Users\username\Projects\proj-venv\lib\site-packages\alabaster\__init__.py
#   recommonmark (0.7.1) from c:\Users\username\Projects\proj-venv\lib\site-packages\recommonmark\__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\ext\autodoc\preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.2.0) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\ext\autodoc\type_comment.py
#   sphinx.ext.autodoc (4.2.0) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\ext\autodoc\__init__.py
#   sphinx.ext.extlinks (4.2.0) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\ext\extlinks.py
#   sphinx.ext.graphviz (4.2.0) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\ext\graphviz.py
#   sphinx.ext.inheritance_diagram (4.2.0) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\ext\inheritance_diagram.py
#   sphinx.ext.intersphinx (4.2.0) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\ext\intersphinx.py
#   sphinx.ext.napoleon (4.2.0) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\ext\napoleon\__init__.py
#   sphinx.ext.todo (4.2.0) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\ext\todo.py
#   sphinx.ext.viewcode (4.2.0) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\ext\viewcode.py
#   sphinx_diagrams (4.2.0) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx_diagrams\__init__.py
#   sphinx_rtd_theme (unknown version) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx_rtd_theme\__init__.py
#   sphinxcontrib.confluencebuilder (1.5.0) from c:\Users\username\Projects\proj-venv\lib\site-packages\sphinxcontrib\confluencebuilder\__init__.py
Traceback (most recent call last):
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\cmd\build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\application.py", line 337, in build
    self.builder.build_all()
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\builders\__init__.py", line 257, in build_all
    self.build(None, summary=__('all source files'), method='all')
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\builders\__init__.py", line 357, in build
    self.write(docnames, list(updated_docnames), method)
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\builders\__init__.py", line 531, in write
    self._write_serial(sorted(docnames))
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\sphinx\builders\__init__.py", line 541, in _write_serial
    self.write_doc(docname, doctree)
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\sphinxcontrib\confluencebuilder\builder.py", line 417, in write_doc
    self.writer.write(doctree, destination)
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\docutils\writers\__init__.py", line 78, in write
    self.translate()
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\sphinxcontrib\confluencebuilder\writer.py", line 24, in translate
    self.document.walkabout(visitor)
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\docutils\nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\docutils\nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\docutils\nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 2 more times]
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\docutils\nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\docutils\nodes.py", line 1995, in dispatch_visit
    return method(node)
  File "c:\Users\username\Projects\proj-venv\lib\site-packages\sphinxcontrib\confluencebuilder\translator\__init__.py", line 132, in unknown_visit
    raise NotImplementedError('unknown node: ' + node_name)
NotImplementedError: unknown node: diagrams
```

### How to Reproduce

Command executed to build and push to confluence:
`sphinx-build -E -a docs/source docs/build/confluence -b confluence`

Contents of 'docs\source\requirements.txt'

```
recommonmark
sphinx
sphinx-diagrams
sphinx-rtd-theme
sphinxcontrib-confluencebuilder
sphinxcontrib-napoleon
```

### Expected behavior

Builds and pushes the sphinx docs to confluence.

### Your project

Confidential.

### OS

Windows 10

### Python version

Python 3.9.4

### Sphinx version

sphinx-build 4.2.0

### Sphinx extensions

[     'recommonmark',     'sphinx.ext.autodoc',     'sphinx.ext.extlinks',     'sphinx.ext.graphviz',     'sphinx.ext.inheritance_diagram',     'sphinx.ext.intersphinx',     'sphinx.ext.napoleon',     'sphinx.ext.todo',     'sphinx.ext.viewcode',     'sphinx_diagrams',     'sphinx_rtd_theme',     'sphinxcontrib.confluencebuilder', ]

### Additional context

This is a confidential project I cannot share on GitHub etc.

**Comment by jdknight** [comment] 2021-12-04 18:33
Changes have been added in #596 to improve user's support when using sphinx-diagrams with this extension. This change has been added into the main branch and should be made available next stable release (v1.8). Users wanting to use sphinx-diagrams before a release is made, the [development version](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation) of this extension can be installed.

A workaround, if desired, is to inject the following in a documentation's configuration:

```
from docutils import nodes
from sphinx_diagrams import DiagramsError
from sphinx_diagrams import diagrams as sphinx_diagrams_diagrams
from sphinx_diagrams import logger as sphinx_diagrams_logger
from sphinx_diagrams import render_diagrams as sphinx_diagrams_render

def generic_visit_diagrams(self, node):
    try:
        fname, _ = sphinx_diagrams_render(
            self, node['code'], node['options'], 'diagrams')
    except DiagramsError as exc:
        sphinx_diagrams_logger.warning('diagrams code %r: ' % node['code'] + str(exc))
        raise nodes.SkipNode

    img_node = nodes.image(uri=fname, alt=node.get('alt', ''))
    if 'align' in node:
        img_node['align'] = node['align']

    new_container = nodes.paragraph()
    new_container.append(img_node)
    node.replace_self(new_container)
    self.visit_image(img_node)

def generic_depart_diagrams(self, node):
    pass

def setup(app):
    app.add_node(sphinx_diagrams_diagrams,
        confluence=(generic_visit_diagrams, generic_depart_diagrams),
        override=True)
```

**Comment by AndreasLuckert** [comment] 2021-12-14 16:53
Dear @jdknight,

after having inserted your workaround in the `conf.py`, the following error occurs:

```
$ sphinx-build -E -a docs/source docs/build/confluence -b confluence
Running Sphinx v4.2.0

sphinxcontrib.confluencebuilder error:
---
An issue has been detected when trying to communicate with Confluence server.

Ensure the server is running or your Confluence server URL is valid:

    https://wiki.<projectname>.com/confluence/

(details: REST reply did not provide valid JSON data.)
---
```

Actually, the error still persists after commenting out all of your workaround, so do you have an idea where this could come from?

**Comment by jdknight** [comment] 2022-01-01 00:24
Typically, a response that does not provide JSON data is either:

1) The Confluence URL is incorrect; or,
2) There is additional proxy/authentication settings required to be set.

A first approach could be to run the report command:

```
python -m sphinxcontrib.confluencebuilder report
```

Which can provide additional information on this extension's attempts to query the Confluence server. Specifically, if it is getting a good response code from the server, can fetch/decode, etc.

You can try to manually query the configured Confluence instance's API point by manually opening a browser to the following URL (based off your provided site example):

```
https://wiki.<projectname>.com/confluence/rest/api/search
```

And you should see a response such as the following:

```
{"statusCode":400,"data":{"authorized":false,"valid":true,"errors":[],"successful":false},"message":"com.atlassian.confluence.api.service.exceptions.BadRequestException: cql query parameter is required"}
```

If you do not see a JSON-like response here, it is most likely that your URL is incorrect. If you do see a proper response here, the issue is most likely an issue with a proxy configuration or other special authentication requirements.

---

If you are in a corporate environment which uses a proxy, you may be require to configure your instance to either use or not use a proxy (depending on how the Confluence instance you are interacting with is located). If you do not have your shell environment configured to use a proxy, you will either want to [set the `https_proxy` variable](https://stackoverflow.com/a/8287752/693291) to use your local proxy or ensure `no_proxy` is set to exclude your Confluence instance (if you do not want to use the proxy).

Alternatively, you can also try to set the proxy via the [`confluence_proxy`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_proxy) configuration option if needed. For example, in your `conf.py`, add:

```
confluence_proxy = 'myawesomeproxy:8080'
```
---

If you are not using a proxy or the proxy configuration is expected to be properly set, there may not be an immediate answer for this issue. A next guess would be that the Confluence instance being talked to requires additional authentication work -- such as instances using a custom single sign-on (SSO) provider. This would require looking at possibly the [`confluence_server_auth`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_server_auth) or [`confluence_server_cookies`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_server_cookies) options, but to know what options you would need to set are specific to the instance (and may require support from your local IT).

**Comment by AndreasLuckert** [comment] 2022-03-11 12:27
Dear @jdknight,
I'd like to ask how things are going regarding the release of version 1.8.
It's been December 1st when I created this issue and it'd be great to close it soon :)

Many thanks in advance for your time and help!

**Comment by jdknight** [comment] 2022-03-12 18:51
The [v1.8](https://github.com/sphinx-contrib/confluencebuilder/milestone/12) release is extremely close. There are three issues remaining open (one needing me to sanity check a corner case, one helping a user with their sign-off state and proxy rate-limiting fix that needs to be done). Ideally, these can be done within this upcoming week ~ and at the latest, I'll say by the end of the month.

**Comment by jdknight** [comment] 2022-03-27 18:02
v1.8 is now available on PyPI -- marking as closed.

**Closed by jdknight** 2022-03-27 18:02 UTC
Labels: enhancement, pending next release, third-party-extension
